spring: 
  profiles: 
    active: 
    - dev
---
server: 
  port: 8001
spring: 
  profiles: dev
  application: 
    name: microservicecloud-config-provider-client-user
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource      # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        # mysql驱动包
    url: jdbc:mysql://localhost:3306/booksystem01       # 数据库名称
    username: root
    password: root
    dbcp2: 
      min-idle: 5                       # 数据库连接池的最小维持连接数
      initial-size: 5                     # 初始化连接数
      max-total: 5                      # 最大连接数
      max-wait-millis: 200                  # 等待连接获取的最大超时时间

mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml      # mybatis配置文件所在路径
  type-aliases-package: com.nikola.springcloud.enetities    # 所有entities别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件
   
###################### 微服务系统搭建 ###########################################################
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/      # 将客户端注册进eureka服务列表内
  instance: 
    instance-id: microservicecloud-user8001         # 默认服务名称修改
    prefer-ip-address: true                 # 访问路径显示IP

info: 
  app.name: nikola-microservicecloud8001
  companyname: www.nikolazhang.xyz
  build.artifactId: $project.artifactId$
  build.version: $project.version$